version: "3.9"

services:
  db:
    image: postgres:17-alpine
    container_name: joongworld-postgres
    environment:
      POSTGRES_DB: joongworld
      POSTGRES_USER: joongworld
      POSTGRES_PASSWORD: "!test1234"   # 특수문자 있으니 반드시 따옴표
      TZ: Asia/Seoul
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"     # host 5432 → container 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U joongworld -d joongworld" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  pgadmin: # (웹에서 DB 확인용 - 테스트용)
    image: dpage/pgadmin4:latest
    container_name: joongworld-pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
      TZ: Asia/Seoul
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAVA_VERSION=21
    container_name: joongworld-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: Asia/Seoul
      # Spring이 자동 인식하는 표준 환경변수 키
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/joongworld
      SPRING_DATASOURCE_USERNAME: joongworld
      SPRING_DATASOURCE_PASSWORD: "!test1234"
    ports:
      - "8080:8080"

volumes:
  pgdata:
  pgadmin: