version: "3.9"

services:
  db:
    image: postgres:17-alpine
    container_name: swboard-postgres
    environment:
      POSTGRES_DB: swboard
      POSTGRES_USER: swboard
      POSTGRES_PASSWORD: "!test1234"   # 특수문자 있으니 반드시 따옴표
      TZ: Asia/Seoul
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"     # host 5432 → container 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swboard -d swboard"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  pgadmin:               # 선택(웹에서 DB 확인용)
    image: dpage/pgadmin4:latest
    container_name: swboard-pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
      TZ: Asia/Seoul
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin:
