-- 서버 재시작 마다 테이블 비우고 더미데이터로 강제셋업
truncate table "user" restart identity cascade;
truncate table post restart identity cascade;
truncate table category restart identity cascade;

-- 카테고리 테이블에 더미삽입
insert into category (name, display_order) values
    ('시계/주얼리', 1),
    ('디지털/가전', 2),
    ('가구/인테리어', 3);

--  포스팅 테이블에 더미삽입
insert into post (category_id, title, price, region, safe_pay, condition_text, description, thumbnail_url, image_urls, created_at)
values
    ((select id from category where name = '시계/주얼리'),
     '롤렉스 익스플로러 I 36mm', 10800000, '서울 강남', true,
     '중고 · 사용감 적음',
     '정기 점검 완료된 제품으로 상태 우수합니다. 보증 카드 포함, 안전결제 가능합니다.',
     'https://picsum.photos/seed/watch01/400/300',
     ARRAY['https://picsum.photos/seed/watch01_1/1200/900','https://picsum.photos/seed/watch01_2/1200/900'],
     now() - interval '2 hours'),

    ((select id from category where name = '시계/주얼리'),
     '태그호이어 까레라 크로노그래프', 4200000, '서울 송파', true,
     '중고 · 양호',
     '풀박스 구성입니다. 생활 스크래치만 존재하며 오버홀 내역 있습니다.',
     'https://picsum.photos/seed/watch02/400/300',
     ARRAY['https://picsum.photos/seed/watch02_1/1200/900','https://picsum.photos/seed/watch02_2/1200/900'],
     now() - interval '6 hours'),

    ((select id from category where name = '시계/주얼리'),
     '오메가 씨마스터 다이버 300M', 6200000, '경기 분당', false,
     '중고 · 가벼운 흠집',
     '케이스에 미세 스크래치 있습니다. 구성품 모두 보유하고 있으며 택배 거래 가능합니다.',
     'https://picsum.photos/seed/watch03/400/300',
     ARRAY['https://picsum.photos/seed/watch03_1/1200/900','https://picsum.photos/seed/watch03_2/1200/900'],
     now() - interval '12 hours'),

    ((select id from category where name = '시계/주얼리'),
     '까르띠에 발롱블랑 33mm', 5800000, '서울 용산', true,
     '중고 · 사용감 적음',
     '오토매틱 모델이며 스트랩 2종 포함입니다. 직거래 선호합니다.',
     'https://picsum.photos/seed/watch04/400/300',
     ARRAY['https://picsum.photos/seed/watch04_1/1200/900','https://picsum.photos/seed/watch04_2/1200/900'],
     now() - interval '1 day'),

    ((select id from category where name = '시계/주얼리'),
     '떼르르 브레이슬릿 세트', 180000, '서울 마포', true,
     '신품 · 미개봉',
     '銀 925 소재로 제작된 브레이슬릿입니다. 쇼핑백과 케이스 그대로 보존되어 있습니다.',
     'https://picsum.photos/seed/watch05/400/300',
     ARRAY['https://picsum.photos/seed/watch05_1/1200/900','https://picsum.photos/seed/watch05_2/1200/900'],
     now() - interval '1 day 6 hours'),

    ((select id from category where name = '시계/주얼리'),
     '애플워치 울트라 2 티타늄', 1090000, '경기 수원', false,
     '중고 · 사용감 적음',
     '배터리 성능 98% 상태이며 스트랩 2종 포함입니다.',
     'https://picsum.photos/seed/watch06/400/300',
     ARRAY['https://picsum.photos/seed/watch06_1/1200/900','https://picsum.photos/seed/watch06_2/1200/900'],
     now() - interval '1 day 12 hours'),

    ((select id from category where name = '시계/주얼리'),
     '세이코 프리미어 문페이즈', 520000, '인천 연수', true,
     '중고 · 양호',
     '2년 사용했습니다. 생활 스크래치 존재하며 정품 보증서 동봉합니다.',
     'https://picsum.photos/seed/watch07/400/300',
     ARRAY['https://picsum.photos/seed/watch07_1/1200/900','https://picsum.photos/seed/watch07_2/1200/900'],
     now() - interval '2 days'),

    ((select id from category where name = '시계/주얼리'),
     '카시오 지샥 GA-2100', 92000, '대전 서구', false,
     '중고 · 생활기스',
     '케이스에 잔기스 있으나 작동 이상 없습니다. 택배 가능해요.',
     'https://picsum.photos/seed/watch08/400/300',
     ARRAY['https://picsum.photos/seed/watch08_1/1200/900','https://picsum.photos/seed/watch08_2/1200/900'],
     now() - interval '2 days 12 hours'),

    ((select id from category where name = '시계/주얼리'),
     '미도 바론첼리 레이디', 360000, '대구 수성', true,
     '중고 · 사용감 적음',
     '오토매틱 모델로 2023년 구입했습니다. 레더 스트랩 포함 구성입니다.',
     'https://picsum.photos/seed/watch09/400/300',
     ARRAY['https://picsum.photos/seed/watch09_1/1200/900','https://picsum.photos/seed/watch09_2/1200/900'],
     now() - interval '3 days'),

    ((select id from category where name = '시계/주얼리'),
     '티쏘 PRX 쿼츠 블루', 420000, '부산 해운대', false,
     '중고 · 양호',
     '박스 풀세트 보유 중이고 추가 링크 포함입니다.',
     'https://picsum.photos/seed/watch10/400/300',
     ARRAY['https://picsum.photos/seed/watch10_1/1200/900','https://picsum.photos/seed/watch10_2/1200/900'],
     now() - interval '3 days 6 hours'),

    ((select id from category where name = '시계/주얼리'),
     '허블롯 클래식 퓨전 42mm', 7800000, '서울 강서', true,
     '중고 · 사용감 적음',
     '오토매틱 모델이며 보증서/케이스 모두 포함된 제품입니다.',
     'https://picsum.photos/seed/watch11/400/300',
     ARRAY['https://picsum.photos/seed/watch11_1/1200/900','https://picsum.photos/seed/watch11_2/1200/900'],
     now() - interval '3 days 12 hours'),

    ((select id from category where name = '시계/주얼리'),
     '브라이틀링 아벤저 GMT', 4900000, '광주 서구', true,
     '중고 · 양호',
     '해외직구 제품입니다. 구성품 모두 있고 사용감 적습니다.',
     'https://picsum.photos/seed/watch12/400/300',
     ARRAY['https://picsum.photos/seed/watch12_1/1200/900','https://picsum.photos/seed/watch12_2/1200/900'],
     now() - interval '4 days'),

    ((select id from category where name = '시계/주얼리'),
     '몽블랑 스타레거시 오토매틱', 1450000, '경기 일산', false,
     '중고 · 생활기스',
     '케이스에 미세 스크래치 존재하며 시계줄 길이 조절 완료했습니다.',
     'https://picsum.photos/seed/watch13/400/300',
     ARRAY['https://picsum.photos/seed/watch13_1/1200/900','https://picsum.photos/seed/watch13_2/1200/900'],
     now() - interval '4 days 8 hours'),

    ((select id from category where name = '시계/주얼리'),
     '노모스 탕젠테 38', 1850000, '서울 광진', true,
     '중고 · 사용감 적음',
     '2022년 구매 제품으로 케이스, 보증서 모두 있습니다.',
     'https://picsum.photos/seed/watch14/400/300',
     ARRAY['https://picsum.photos/seed/watch14_1/1200/900','https://picsum.photos/seed/watch14_2/1200/900'],
     now() - interval '5 days'),

    ((select id from category where name = '시계/주얼리'),
     '빈티지 실버 뱅글', 98000, '서울 종로', true,
     '중고 · 생활기스',
     '기스 있는 편이지만 착용감 좋습니다. 실버 925 마크 확인 가능합니다.',
     'https://picsum.photos/seed/watch15/400/300',
     ARRAY['https://picsum.photos/seed/watch15_1/1200/900','https://picsum.photos/seed/watch15_2/1200/900'],
     now() - interval '5 days 6 hours'),

    ((select id from category where name = '시계/주얼리'),
     '판도라 참 세트', 135000, '서울 서초', false,
     '중고 · 양호',
     '다양한 참으로 구성된 세트입니다. 케이스 포함입니다.',
     'https://picsum.photos/seed/watch16/400/300',
     ARRAY['https://picsum.photos/seed/watch16_1/1200/900','https://picsum.photos/seed/watch16_2/1200/900'],
     now() - interval '6 days'),

    ((select id from category where name = '시계/주얼리'),
     '다니엘웰링턴 클래식 블랙', 82000, '서울 중구', true,
     '중고 · 사용감 적음',
     '한 달 사용 후 보관만 했습니다. 기본 스트랩 포함입니다.',
     'https://picsum.photos/seed/watch17/400/300',
     ARRAY['https://picsum.photos/seed/watch17_1/1200/900','https://picsum.photos/seed/watch17_2/1200/900'],
     now() - interval '6 days 12 hours'),

    ((select id from category where name = '시계/주얼리'),
     '구찌 인터로킹 팔찌', 210000, '서울 성동', true,
     '중고 · 양호',
     '정품보증 카드 있습니다. 직접 착용 사진 요청 시 보내드립니다.',
     'https://picsum.photos/seed/watch18/400/300',
     ARRAY['https://picsum.photos/seed/watch18_1/1200/900','https://picsum.photos/seed/watch18_2/1200/900'],
     now() - interval '7 days'),

    ((select id from category where name = '시계/주얼리'),
     '골든듀 목걸이 세트', 320000, '서울 동작', true,
     '중고 · 사용감 적음',
     '14K 제품이며 원본 케이스와 보증서 제공드립니다.',
     'https://picsum.photos/seed/watch19/400/300',
     ARRAY['https://picsum.photos/seed/watch19_1/1200/900','https://picsum.photos/seed/watch19_2/1200/900'],
     now() - interval '7 days 8 hours'),

    ((select id from category where name = '시계/주얼리'),
     '스와로브스키 크리스털 이어링', 75000, '서울 강북', false,
     '중고 · 생활기스',
     '사용감 있는 편이며 교환/환불 불가합니다.',
     'https://picsum.photos/seed/watch20/400/300',
     ARRAY['https://picsum.photos/seed/watch20_1/1200/900','https://picsum.photos/seed/watch20_2/1200/900'],
     now() - interval '7 days 12 hours'),

    ((select id from category where name = '디지털/가전'),
     '닌텐도 스위치 OLED 네온', 360000, '부산 해운대', false,
     '중고 · 생활기스',
     '박스/구성품 완비, 성능 이상 없음. 택배 가능하며 직거래는 해운대역에서 가능합니다.',
     'https://picsum.photos/seed/switch/400/300',
     ARRAY['https://picsum.photos/seed/switch1/1200/900','https://picsum.photos/seed/switch2/1200/900'],
     now() - interval '1 day'),

    ((select id from category where name = '디지털/가전'),
     '아이패드 에어 5세대 64GB 스카이블루', 720000, '대구 수성', true,
     '중고 · 사용감 적음',
     '유튜브 시청 용도로만 사용해서 상태가 깨끗합니다. 애플케어 남아있으며, 스마트폴리오 함께 드립니다.',
     'https://picsum.photos/seed/ipad/400/300',
     ARRAY['https://picsum.photos/seed/ipad1/1200/900','https://picsum.photos/seed/ipad2/1200/900'],
     now() - interval '5 hours'),

    ((select id from category where name = '가구/인테리어'),
     '스탠딩 책상 (1200폭)', 140000, '인천 송도', false,
     '중고 · 양호',
     '높이 조절 가능한 전동 스탠딩 책상입니다. 분해 후 차량에 실어 드릴 수 있습니다.',
     'https://picsum.photos/seed/desk/400/300',
     ARRAY['https://picsum.photos/seed/desk1/1200/900','https://picsum.photos/seed/desk2/1200/900'],
     now() - interval '12 hours');
